SRCS := $(wildcard src/*.md)
CHAPTERS := $(patsubst src/%.md, out/%.tex, $(SRCS))

PANDOC_FLAGS := --citeproc

.PHONY: all
.PHONY: clean

all: out/handout.pdf

out/handout.pdf: handout.tex pandoc.tex $(CHAPTERS)
	pdflatex -output-directory=out handout.tex

out/%.tex: src/%.md out
	pandoc $(PANDOC_FLAGS) -o $@ $<

out:
	mkdir -p out

clean:
	rm -f out/*


