SRCS := $(wildcard src/*.md)
CHAPTERS := $(patsubst src/%.md, out/%.tex, $(SRCS))

PANDOC_FLAGS := --citeproc --lua-filter=filters/callout2latex.lua

.PHONY: all clean

all: handout.pdf

handout.pdf: out/handout.pdf
	cp $< $@

out/handout.pdf: handout.tex pandoc.tex $(CHAPTERS) | out
# 	pdflatex -output-directory=out handout.tex
	latexmk -pdf -output-directory=out handout.tex

out/%.tex: src/%.md | out
	pandoc $(PANDOC_FLAGS) -o $@ $<

out:
	mkdir -p out

clean:
	rm -f handout.pdf
	rm -rf out


